=== notkisk/xml-tp1/Faculty.dtd
<!ELEMENT Faculty (student+)>
    <!ELEMENT student (firstName, familyName, age, addresse, 
                       level, speciality, average)>
    <!ATTLIST student registrationNumber CDATA #REQUIRED>
    <!ELEMENT firstName (#PCDATA)>
    <!ELEMENT familyName (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT addresse (number, city, postalCode)>
    <!ELEMENT number (#PCDATA)>
    <!ELEMENT city (#PCDATA)>
    <!ELEMENT postalCode (#PCDATA)>
    <!ELEMENT level (#PCDATA)>
    <!ELEMENT speciality (#PCDATA)>
    <!ELEMENT average (#PCDATA)>

=== notkisk/xml-tp1/Stuendts.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Faculty SYSTEM "Faculty.dtd"> 
<Faculty>
	<student registrationNumber="39074561">
		<firstName>Haithem</firstName>
		<familyName>Bekkari</familyName>
		<age>23</age>
		<addresse>
			<number>6465464665</number>
			<city>bayadha</city>
			<postalCode>39007</postalCode>
		</addresse>
		<level>L1</level>
		<speciality>"ComputerScience"</speciality>
		<average>12.95</average>
	</student>
	<student registrationNumber="39074561">
		<firstName>Haithem</firstName>
		<familyName>Bekkari</familyName>
		<age>23</age>
		<addresse>
			<number>6465464665</number>
			<city>bayadha</city>
			<postalCode>39007</postalCode>
		</addresse>
		<level>l3</level>
		<speciality>"ComputerScience"</speciality>
		<average>12.95</average>
	</student>


</Faculty>
